name: Build and Publish image to docker hub
on: 
  push

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t . koili-scripts:latest
